# Site settings
title: Product Logs # site title
description: >- # site description
  who likes clothes and shoes
  <a href="https://github.com/myungseokang" target="_blank" rel="noopener">@github</a>.
lang: ko-KR # default lang
timezone: Asia/Seoul # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/myungseokang/product # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Myungseo Kang # author name
  bio: >- # tell to the world
    who likes clothes and shoes
    <a href="https://github.com/myugnseokang/product" target="_blank" rel="noopener">@github</a>.
  username: myungseokang # general username
  github: myungseokang # github username
  twitter: myungseokang # twitter username
  facebook: myungseokang7 # facebook username
  email: iam@myungseokang.space # email adress
  linkedin: myungseokang # linkedin username
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://product.myungseokang.space" #
baseurl:
permalink: /:title/
google_analytics: G-8WT0W97L72 # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 10

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
